nombre1=input("Ingresa tu primer nombre: ")
nombre2=input("Ingresa tu segundo nombre: ")
apellido1=input("Ingresa tu primer Apellido: ")
apellido2=input("Ingresa tu segundo Apellido: ")

nombrecompleto=str(nombre1 + nombre2 +apellido1 +apellido2)
print ("------------------------")
print("hola " + nombrecompleto)
print ("------------------------")
print("hola :")
print(nombre1)
print(nombre2)
print(apellido1)
print(apellido2)
print ("------------------------")
print("hola :" + nombre1 + nombre2 + apellido1 + apellido2)
print ("------------------------")
print("hola :" + nombre1+ " " + nombre2+ " " + apellido1+ " " + apellido2)
#aporte de 
print ("------------------------")
print("hola :"+ nombre1, nombre2, apellido1,  apellido2)