nombre=input("ingresa tu nombre: ")
print ("convertir mayusculas")
print (nombre.upper())
print ("primera mayuscula mayusculas")
print (nombre.capitalize())
nombre=nombre.capitalize()
nombre=nombre.strip()
print ("caracter señalado")
print(str(nombre[0]))
print("numero de caracteres")
print(len(nombre))